export { default as HomeIcon } from "./HomeIcon"
export { default as ProductsIcon } from "./ProductsIcon"
export { default as CategoriesIcon } from "./CategoriesIcon"
export { default as OriginsIcon } from "./OriginsIcon"
export { default as TerritoriesIcon } from "./TerritoriesIcon"
export { default as TransporterIcon } from "./TransporterIcon"
export { default as LogoutIcon } from "./LogoutIcon"
