services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./apps/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - db

  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000

  db:
    image: ghcr.io/tursodatabase/libsql-server:v0.24.14
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
