services:
  db:
    image: postgres:18.4-alpine
    container_name: taxdom_db
    restart: unless-stopped
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:8.6.4-alpine
    container_name: taxdom_redis
    restart: unless-stopped
    ports:
      - 6379:6379
