services:
  nginx:
    image: nginx:1.29.0-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apps/nginx/taxdom.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/nginx/api.taxdom.conf:/etc/nginx/conf.d/api.taxdom.conf:ro
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/cf/taxdom.pem:/etc/nginx/ssl/taxdom.pem:ro
      - /etc/ssl/cf/taxdom.key:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - web
      - api
      # - blog // Blog service is not vital
    networks:
      - frontend
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=50m
      - /var/run:rw,noexec,nosuid,size=50m

  web:
    image: ghcr.io/zeis974/taxdom-web:latest
    restart: unless-stopped
    expose:
      - 3000
    secrets:
      - web_env
    environment:
      - NODE_ENV=production
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50m

  api:
    image: ghcr.io/zeis974/taxdom-api:latest
    restart: unless-stopped
    expose:
      - 3333
    secrets:
      - api_env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50m

  blog:
    image: ghcr.io/zeis974/taxdom-blog:latest
    restart: unless-stopped
    expose:
      - 4321
    environment:
      - NODE_ENV=production
    volumes:
      - blog_volume:/app/dist
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50m

  redis:
    image: redis:8.0.3-alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50m

  db:
    image: ghcr.io/tursodatabase/libsql-server:cda864e
    restart: unless-stopped
    expose:
      - 8080
      - 5001
    volumes:
      - db_data:/var/lib/sqld
    secrets:
      - db_env
    networks:
      - backend
    security_opt:
      - no-new-privileges:true

networks:
  frontend:
    driver: bridge
    internal: false
  backend:
    driver: bridge
    internal: true

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
  blog_volume:
    driver: local

secrets:
  web_env:
    file: .env.web.prod
  api_env:
    file: .env.api.prod
  db_env:
    file: .env.db.prod
