services:
  nginx:
    image: nginx:1.27.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apps/nginx/taxdom.conf:/etc/nginx/conf.d/default.conf
      - ./apps/nginx/api.taxdom.conf:/etc/nginx/conf.d/api.taxdom.conf
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/cf/taxdom.pem:/etc/nginx/ssl/taxdom.pem
      - /etc/ssl/cf/taxdom.key:/etc/nginx/ssl/key.pem
    depends_on:
      - web
      - api
      - db

  web:
    image: ghcr.io/zeis974/taxdom-web:latest
    ports:
      - 3000:3000
    env_file:
      - .env.web.prod

  api:
    image: ghcr.io/zeis974/taxdom-api:latest
    ports:
      - 3333:3333
    env_file:
      - .env.api.prod

  redis:
    image: redis:7.4.2-alpine
    ports:
      - 6379:6379

  db:
    image: ghcr.io/tursodatabase/libsql-server:v0.24.32
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./data/libsql:/var/lib/sqld
    env_file:
      - .env.db.prod
