services:
  nginx:
    image: nginx:1.27.1-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./apps/nginx/taxdom.conf:/etc/nginx/conf.d/default.conf
      - ./apps/nginx/api.taxdom.conf:/etc/nginx/conf.d/api.taxdom.conf
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api
      - db

  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - 3000:3000

  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 3333:3333
    env_file:
      - apps/api/.env

  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    ports:
      - 6379:6379

  db:
    image: ghcr.io/tursodatabase/libsql-server:v0.24.25
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
