services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apps/nginx/taxdom.conf:/etc/nginx/conf.d/default.conf
      - ./apps/nginx/api.taxdom.conf:/etc/nginx/conf.d/api.taxdom.conf
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api
      - db

  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000

  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    ports:
      - 3333:3333

  db:
    image: ghcr.io/tursodatabase/libsql-server:v0.24.20
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqld
