services:
  nginx:
    image: nginx:1.27.1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apps/nginx/taxdom.conf:/etc/nginx/conf.d/default.conf
      - ./apps/nginx/api.taxdom.conf:/etc/nginx/conf.d/api.taxdom.conf
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/cf/taxdom.pem:/etc/nginx/conf.d/taxdom.pem
      - /etc/ssl/cf/taxdom.key:/etc/nginx/conf.d/key.pem
    depends_on:
      - web
      - api
      - db

  web:
    image: ghcr.io/zeis974/taxdom-web:latest
    ports:
      - 3000:3000
    env_file:
      - .env.production

  api:
    image: ghcr.io/zeis974/taxdom-api:latest
    ports:
      - 3333:3333
    secrets:
      - API_KEY
      - APP_KEY
    environment:
      API_KEY: /run/secrets/API_KEY
      APP_KEY: /run/secrets/APP_KEY
      DB_URL: http://db:8080
      HOST: 0.0.0.0
      LOG_LEVEL: info
      PORT: 3333
      LIMITER_STORE: redis
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      SESSION_DRIVER: cookie

  redis:
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379

  db:
    image: ghcr.io/tursodatabase/libsql-server:v0.24.25
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqld

secrets:
  API_KEY:
    external: true
  APP_KEY:
    external: true
