version: "3.8"

services:
  nginx:
    image: nginx:1.25.4-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apps/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - database

  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000

  database:
    container_name: database
    image: mariadb:11.2.2
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
