services:
  nginx:
    image: nginx:1.28.0-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./apps/nginx/taxdom.conf:/etc/nginx/ssl/default.conf
      - ./apps/nginx/api.taxdom.conf:/etc/nginx/ssl/api.taxdom.conf
      - ./apps/nginx/taxdom.conf:/etc/nginx/conf.d/default.conf
      - ./apps/nginx/api.taxdom.conf:/etc/nginx/conf.d/api.taxdom.conf
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - blog_volume:/usr/share/nginx/html
    depends_on:
      - web
      - api
      - db

  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - apps/web/.env

  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 3333:3333
    env_file:
      - apps/api/.env

  blog:
    container_name: blog
    build:
      context: .
      dockerfile: apps/blog/Dockerfile
    ports:
      - 4231:4231
    volumes:
      - blog_volume:/app/dist

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    ports:
      - 6379:6379

  db:
    image: ghcr.io/tursodatabase/libsql-server:395b2ca
    container_name: db
    platform: linux/amd64
    ports:
      - 8080:8080
      - 5001:5001
    env_file:
      - apps/api/.env

volumes:
  blog_volume:
