/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  CalculateParcel: () => import("#controllers/CalculateParcelController"),
  Categories: () => import("#controllers/CategoriesController"),
  GetProductTaxes: () => import("#controllers/GetProductTaxesController"),
  GetTemplates: () => import("#controllers/GetTemplatesController"),
  Origins: () => import("#controllers/OriginsController"),
  Products: () => import("#controllers/ProductsController"),
  SearchConfig: () => import("#controllers/SearchConfigController"),
  Transporters: () => import("#controllers/TransportersController"),
  Territories: () => import("#controllers/TerritoriesController"),
  SearchProducts: () => import("#controllers/SearchProductsController"),
  TransporterRules: () => import("#controllers/TransporterRulesController"),
}
