/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  CalculateParcel: () => import('#controllers/CalculateParcelController'),
  Categories: () => import('#controllers/CategoriesController'),
  CustomsNomenclatures: () => import('#controllers/CustomsNomenclaturesController'),
  GetNomenclatureTaxes: () => import('#controllers/GetNomenclatureTaxesController'),
  GetProductTaxes: () => import('#controllers/GetProductTaxesController'),
  GetTemplates: () => import('#controllers/GetTemplatesController'),
  Origins: () => import('#controllers/OriginsController'),
  Products: () => import('#controllers/ProductsController'),
  ResolveProductTaxes: () => import('#controllers/ResolveProductTaxesController'),
  ScrapeProductUrl: () => import('#controllers/ScrapeProductUrlController'),
  SearchProducts: () => import('#controllers/SearchProductsController'),
  Territories: () => import('#controllers/TerritoriesController'),
  TransporterRules: () => import('#controllers/TransporterRulesController'),
  Transporters: () => import('#controllers/TransportersController'),
}
