/**
 * Country flags — maps the French country name (as stored in `origins`) to
 * its ISO 3166-1 alpha-2 code (lowercase), used by `flag-icons`.
 *
 * The lookup key is normalized (accents stripped, uppercased, separators
 * removed) to tolerate variants stored in the database: "GRÈCE" and "GRECE"
 * both resolve to "gr".
 */

const RAW_COUNTRY_FLAGS: Record<string, string> = {
  ALLEMAGNE: "de",
  AUTRICHE: "at",
  BELGIQUE: "be",
  BULGARIE: "bg",
  CHYPRE: "cy",
  CROATIE: "hr",
  DANEMARK: "dk",
  ESPAGNE: "es",
  ESTONIE: "ee",
  FINLANDE: "fi",
  FRANCE: "fr",
  GRÈCE: "gr",
  HONGRIE: "hu",
  IRLANDE: "ie",
  ITALIE: "it",
  LETTONIE: "lv",
  LITUANIE: "lt",
  LUXEMBOURG: "lu",
  MALTE: "mt",
  "PAYS-BAS": "nl",
  POLOGNE: "pl",
  PORTUGAL: "pt",
  "RÉPUBLIQUE TCHÈQUE": "cz",
  ROUMANIE: "ro",
  SLOVAQUIE: "sk",
  SLOVÉNIE: "si",
  SUÈDE: "se",
  ANDORRE: "ad",
  ARMÉNIE: "am",
  AZERBAÏDJAN: "az",
  BÉLARUS: "by",
  "BOSNIE-HERZÉGOVINE": "ba",
  GÉORGIE: "ge",
  ISLANDE: "is",
  KOSOVO: "xk",
  LIECHTENSTEIN: "li",
  "MACÉDOINE DU NORD": "mk",
  MOLDAVIE: "md",
  MONACO: "mc",
  MONTÉNÉGRO: "me",
  NORVÈGE: "no",
  "ROYAUME-UNI": "gb",
  RUSSIE: "ru",
  "SAINT-MARIN": "sm",
  SERBIE: "rs",
  SUISSE: "ch",
  UKRAINE: "ua",
  TURQUIE: "tr",
  KAZAKHSTAN: "kz",
  ALBANIE: "al",
  "ANTIGUA-ET-BARBUDA": "ag",
  ARGENTINE: "ar",
  BAHAMAS: "bs",
  BARBADE: "bb",
  BELIZE: "bz",
  BOLIVIE: "bo",
  BRÉSIL: "br",
  CANADA: "ca",
  CHILI: "cl",
  COLOMBIE: "co",
  "COSTA RICA": "cr",
  CUBA: "cu",
  DOMINIQUE: "dm",
  ÉQUATEUR: "ec",
  "ÉTATS-UNIS": "us",
  GRENADE: "gd",
  GUATEMALA: "gt",
  GUYANA: "gy",
  HAÏTI: "ht",
  HONDURAS: "hn",
  JAMAÏQUE: "jm",
  MEXIQUE: "mx",
  NICARAGUA: "ni",
  PANAMA: "pa",
  PARAGUAY: "py",
  PÉROU: "pe",
  "RÉPUBLIQUE DOMINICAINE": "do",
  "SAINT-CHRISTOPHE-ET-NIÉVÈS": "kn",
  "SAINTE-LUCIE": "lc",
  "SAINT-VINCENT-ET-LES-GRENADINES": "vc",
  SALVADOR: "sv",
  SURINAME: "sr",
  "TRINITÉ-ET-TOBAGO": "tt",
  URUGUAY: "uy",
  VENEZUELA: "ve",
  "AFRIQUE DU SUD": "za",
  ALGÉRIE: "dz",
  ANGOLA: "ao",
  BÉNIN: "bj",
  BOTSWANA: "bw",
  "BURKINA FASO": "bf",
  BURUNDI: "bi",
  "CABO VERDE": "cv",
  CAMEROUN: "cm",
  COMORES: "km",
  CONGO: "cg",
  "RÉPUBLIQUE DÉMOCRATIQUE DU CONGO": "cd",
  "CÔTE D'IVOIRE": "ci",
  DJIBOUTI: "dj",
  ÉGYPTE: "eg",
  ÉRYTHRÉE: "er",
  ESWATINI: "sz",
  ÉTHIOPIE: "et",
  GABON: "ga",
  GAMBIE: "gm",
  GHANA: "gh",
  GUINÉE: "gn",
  "GUINÉE-BISSAU": "gw",
  "GUINÉE ÉQUATORIALE": "gq",
  KENYA: "ke",
  LESOTHO: "ls",
  LIBÉRIA: "lr",
  LIBYE: "ly",
  MADAGASCAR: "mg",
  MALAWI: "mw",
  MALI: "ml",
  MAURITANIE: "mr",
  MAURICE: "mu",
  MAROC: "ma",
  MOZAMBIQUE: "mz",
  NAMIBIE: "na",
  NIGER: "ne",
  NIGÉRIA: "ng",
  OUGANDA: "ug",
  "RÉPUBLIQUE CENTRAFRICAINE": "cf",
  RWANDA: "rw",
  "SÃO TOMÉ-ET-PRINCIPE": "st",
  SÉNÉGAL: "sn",
  SEYCHELLES: "sc",
  "SIERRA LEONE": "sl",
  SOMALIE: "so",
  SOUDAN: "sd",
  "SOUDAN DU SUD": "ss",
  TANZANIE: "tz",
  TCHAD: "td",
  TOGO: "tg",
  TUNISIE: "tn",
  ZAMBIE: "zm",
  ZIMBABWE: "zw",
  "ARABIE SAOUDITE": "sa",
  BAHREÏN: "bh",
  BANGLADESH: "bd",
  BHOUTAN: "bt",
  BRUNEI: "bn",
  CAMBODGE: "kh",
  CHINE: "cn",
  "CORÉE DU NORD": "kp",
  "CORÉE DU SUD": "kr",
  "ÉMIRATS ARABES UNIS": "ae",
  INDE: "in",
  INDONÉSIE: "id",
  IRAK: "iq",
  IRAN: "ir",
  ISRAËL: "il",
  JAPON: "jp",
  JORDANIE: "jo",
  KIRGHIZISTAN: "kg",
  KOWEÏT: "kw",
  LAOS: "la",
  LIBAN: "lb",
  MALAISIE: "my",
  MALDIVES: "mv",
  MONGOLIE: "mn",
  MYANMAR: "mm",
  NÉPAL: "np",
  OMAN: "om",
  OUZBÉKISTAN: "uz",
  PAKISTAN: "pk",
  PALESTINE: "ps",
  PHILIPPINES: "ph",
  QATAR: "qa",
  SINGAPOUR: "sg",
  "SRI LANKA": "lk",
  SYRIE: "sy",
  TADJIKISTAN: "tj",
  THAÏLANDE: "th",
  "TIMOR-LESTE": "tl",
  TURKMÉNISTAN: "tm",
  "VIÊT NAM": "vn",
  YÉMEN: "ye",
  AUSTRALIE: "au",
  FIDJI: "fj",
  KIRIBATI: "ki",
  MICRONÉSIE: "fm",
  NAURU: "nr",
  "NOUVELLE-ZÉLANDE": "nz",
  PALAOS: "pw",
  "PAPOUASIE-NOUVELLE-GUINÉE": "pg",
  SAMOA: "ws",
  "ÎLES SALOMON": "sb",
  TONGA: "to",
  TUVALU: "tv",
  VANUATU: "vu",
  VATICAN: "va",
}

/** Normalizes a country name into a lookup key (accents and separators stripped). */
export function normalizeCountryName(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[\s'’\-–—_·]/g, "")
    .toUpperCase()
}

export const COUNTRY_FLAGS: Readonly<Record<string, string>> = Object.fromEntries(
  Object.entries(RAW_COUNTRY_FLAGS).map(([name, iso]) => [normalizeCountryName(name), iso]),
)

/**
 * Returns a country's ISO 3166-1 alpha-2 code (lowercase) from its French
 * name, or `undefined` if the country isn't mapped (yet).
 */
export function getCountryFlag(countryName: string): string | undefined {
  return COUNTRY_FLAGS[normalizeCountryName(countryName)]
}
