export const OriginData = [
  { name: "EU", available: true },
  { name: "HORS_EU", available: true },
  { name: "AFGHANISTAN", available: true },
  { name: "ALBANIE", available: true },
  { name: "ALGERIE", available: true },
  { name: "SAMOA AMERICAINES", available: true },
  { name: "ANDORRE", available: true },
  { name: "ANGOLA", available: true },
  { name: "ANGUILLA", available: true },
  { name: "ANTARCTIQUE", available: true },
  { name: "ANTIGUA-ET-BARBUDA", available: true },
  { name: "ARGENTINE", available: true },
  { name: "ARMENIE", available: true },
  { name: "ARUBA", available: true },
  { name: "AUSTRALIE", available: true },
  { name: "AUTRICHE", available: true },
  { name: "AZERBAIDJAN", available: true },
  { name: "BAHAMAS", available: true },
  { name: "BAHREIN", available: true },
  { name: "BANGLADESH", available: true },
  { name: "BARBADE", available: true },
  { name: "BIELORUSSIE", available: true },
  { name: "BELGIQUE", available: true },
  { name: "BELIZE", available: true },
  { name: "BENIN", available: true },
  { name: "BERMUDES", available: true },
  { name: "BHOUTAN", available: true },
  { name: "BOLIVIE", available: true },
  { name: "BONAIRE, SAINT-EUSTACHE ET SABA", available: true },
  { name: "BOSNIE-HERZEGOVINE", available: true },
  { name: "BOTSWANA", available: true },
  { name: "ILE BOUVET", available: true },
  { name: "BRESIL", available: true },
  { name: "TERRITOIRE BRITANNIQUE DE L'OCEAN INDIEN", available: true },
  { name: "BRUNEI", available: true },
  { name: "BULGARIE", available: true },
  { name: "BURKINA FASO", available: true },
  { name: "BURUNDI", available: true },
  { name: "CAP-VERT", available: true },
  { name: "CAMBODGE", available: true },
  { name: "CAMEROUN", available: true },
  { name: "CANADA", available: true },
  { name: "ILES CAIMANS", available: true },
  { name: "REPUBLIQUE CENTRAFRICAINE", available: true },
  { name: "TCHAD", available: true },
  { name: "CHILI", available: true },
  { name: "CHINE", available: true },
  { name: "ILE CHRISTMAS", available: true },
  { name: "ILES COCOS", available: true },
  { name: "COLOMBIE", available: true },
  { name: "COMORES", available: true },
  { name: "REPUBLIQUE DEMOCRATIQUE DU CONGO", available: true },
  { name: "CONGO", available: true },
  { name: "ILES COOK", available: true },
  { name: "COSTA RICA", available: true },
  { name: "CROATIE", available: true },
  { name: "CUBA", available: true },
  { name: "CURACAO", available: true },
  { name: "CHYPRE", available: true },
  { name: "REPUBLIQUE TCHEQUE", available: true },
  { name: "COTE D'IVOIRE", available: true },
  { name: "DANEMARK", available: true },
  { name: "DJIBOUTI", available: true },
  { name: "DOMINIQUE", available: true },
  { name: "REPUBLIQUE DOMINICAINE", available: true },
  { name: "EQUATEUR", available: true },
  { name: "EGYPTE", available: true },
  { name: "SALVADOR", available: true },
  { name: "GUINEE EQUATORIALE", available: true },
  { name: "ERYTHREE", available: true },
  { name: "ESTONIE", available: true },
  { name: "ESWATINI", available: true },
  { name: "ETHIOPIE", available: true },
  { name: "ILES MALOUINES", available: true },
  { name: "ILES FEROE", available: true },
  { name: "FIDJI", available: true },
  { name: "FINLANDE", available: true },
  { name: "FRANCE", available: true },
  { name: "GUYANE FRANCAISE", available: true },
  { name: "POLYNESIE FRANCAISE", available: true },
  { name: "TERRES AUSTRALES FRANCAISES", available: true },
  { name: "GABON", available: true },
  { name: "GAMBIE", available: true },
  { name: "GEORGIE", available: true },
  { name: "ALLEMAGNE", available: true },
  { name: "GHANA", available: true },
  { name: "GIBRALTAR", available: true },
  { name: "GRECE", available: true },
  { name: "GROENLAND", available: true },
  { name: "GRENADE", available: true },
  { name: "GUADELOUPE", available: true },
  { name: "GUAM", available: true },
  { name: "GUATEMALA", available: true },
  { name: "GUERNESEY", available: true },
  { name: "GUINEE", available: true },
  { name: "GUINEE-BISSAU", available: true },
  { name: "GUYANA", available: true },
  { name: "HAITI", available: true },
  { name: "ILES HEARD-ET-MACDONALD", available: true },
  { name: "SAINT-SIEGE", available: true },
  { name: "HONDURAS", available: true },
  { name: "HONG KONG", available: true },
  { name: "HONGRIE", available: true },
  { name: "ISLANDE", available: true },
  { name: "INDE", available: true },
  { name: "INDONESIE", available: true },
  { name: "IRAN", available: true },
  { name: "IRAK", available: true },
  { name: "IRLANDE", available: true },
  { name: "ILE DE MAN", available: true },
  { name: "ISRAEL", available: true },
  { name: "ITALIE", available: true },
  { name: "JAMAIQUE", available: true },
  { name: "JAPON", available: true },
  { name: "JERSEY", available: true },
  { name: "JORDANIE", available: true },
  { name: "KAZAKHSTAN", available: true },
  { name: "KENYA", available: true },
  { name: "KIRIBATI", available: true },
  { name: "COREE DU NORD", available: true },
  { name: "COREE DU SUD", available: true },
  { name: "KOWEIT", available: true },
  { name: "KIRGHIZISTAN", available: true },
  { name: "LAOS", available: true },
  { name: "LETTONIE", available: true },
  { name: "LIBAN", available: true },
  { name: "LESOTHO", available: true },
  { name: "LIBERIA", available: true },
  { name: "LIBYE", available: true },
  { name: "LIECHTENSTEIN", available: true },
  { name: "LITUANIE", available: true },
  { name: "LUXEMBOURG", available: true },
  { name: "MACAO", available: true },
  { name: "MADAGASCAR", available: true },
  { name: "MALAWI", available: true },
  { name: "MALAISIE", available: true },
  { name: "MALDIVES", available: true },
  { name: "MALI", available: true },
  { name: "MALTE", available: true },
  { name: "ILES MARSHALL", available: true },
  { name: "MARTINIQUE", available: true },
  { name: "MAURITANIE", available: true },
  { name: "MAURICE", available: true },
] as const

export const TerritoryData = [
  { name: "CORSE", available: false },
  { name: "FRANCE", available: false },
  { name: "GUADELOUPE", available: false },
  { name: "GUYANE", available: false },
  { name: "MARTINIQUE", available: false },
  { name: "MAYOTTE", available: false },
  { name: "REUNION", available: true },
] as const

export const TransporterData = [
  { name: "CHRONOPOST", available: true },
  { name: "COLISSIMO", available: true },
  { name: "DHL", available: false },
  { name: "FEDEX", available: false },
] as const

export type Origin = (typeof OriginData)[number]["name"]
export type Territory = (typeof TerritoryData)[number]["name"]
export type Transporter = (typeof TransporterData)[number]["name"]

export type TaxSimulatorResult = {
  product: string
  taxes: {
    tva: number
    om: number
    omr: number
  }
}

export type ParcelSimulatorResult = {
  carrierFee: number
  dutyPrice: number
  totalTaxes: number
  taxes: {
    applicable: "yes" | "no" | "maybe"
    om: number
    omr: number
    tva: number
  }
  products: {
    name: string
    price: number
  }[]
}
