/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginLayoutRouteImport } from './routes/_login-layout'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard-layout'
import { Route as DashboardLayoutIndexRouteImport } from './routes/_dashboard-layout/index'
import { Route as LoginLayoutLoginRouteImport } from './routes/_login-layout/login'
import { Route as DashboardLayoutTransportersRouteImport } from './routes/_dashboard-layout/transporters'
import { Route as DashboardLayoutTerritoriesRouteImport } from './routes/_dashboard-layout/territories'
import { Route as DashboardLayoutProductsRouteImport } from './routes/_dashboard-layout/products'
import { Route as DashboardLayoutOriginsRouteImport } from './routes/_dashboard-layout/origins'
import { Route as DashboardLayoutCategoriesRouteImport } from './routes/_dashboard-layout/categories'
import { Route as DashboardLayoutTransportersEditorIdRouteImport } from './routes/_dashboard-layout/transporters/editor.$id'

const LoginLayoutRoute = LoginLayoutRouteImport.update({
  id: '/_login-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const LoginLayoutLoginRoute = LoginLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LoginLayoutRoute,
} as any)
const DashboardLayoutTransportersRoute =
  DashboardLayoutTransportersRouteImport.update({
    id: '/transporters',
    path: '/transporters',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutTerritoriesRoute =
  DashboardLayoutTerritoriesRouteImport.update({
    id: '/territories',
    path: '/territories',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutProductsRoute = DashboardLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutOriginsRoute = DashboardLayoutOriginsRouteImport.update({
  id: '/origins',
  path: '/origins',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutCategoriesRoute =
  DashboardLayoutCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutTransportersEditorIdRoute =
  DashboardLayoutTransportersEditorIdRouteImport.update({
    id: '/editor/$id',
    path: '/editor/$id',
    getParentRoute: () => DashboardLayoutTransportersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardLayoutIndexRoute
  '/categories': typeof DashboardLayoutCategoriesRoute
  '/origins': typeof DashboardLayoutOriginsRoute
  '/products': typeof DashboardLayoutProductsRoute
  '/territories': typeof DashboardLayoutTerritoriesRoute
  '/transporters': typeof DashboardLayoutTransportersRouteWithChildren
  '/login': typeof LoginLayoutLoginRoute
  '/transporters/editor/$id': typeof DashboardLayoutTransportersEditorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardLayoutIndexRoute
  '/categories': typeof DashboardLayoutCategoriesRoute
  '/origins': typeof DashboardLayoutOriginsRoute
  '/products': typeof DashboardLayoutProductsRoute
  '/territories': typeof DashboardLayoutTerritoriesRoute
  '/transporters': typeof DashboardLayoutTransportersRouteWithChildren
  '/login': typeof LoginLayoutLoginRoute
  '/transporters/editor/$id': typeof DashboardLayoutTransportersEditorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard-layout': typeof DashboardLayoutRouteWithChildren
  '/_login-layout': typeof LoginLayoutRouteWithChildren
  '/_dashboard-layout/categories': typeof DashboardLayoutCategoriesRoute
  '/_dashboard-layout/origins': typeof DashboardLayoutOriginsRoute
  '/_dashboard-layout/products': typeof DashboardLayoutProductsRoute
  '/_dashboard-layout/territories': typeof DashboardLayoutTerritoriesRoute
  '/_dashboard-layout/transporters': typeof DashboardLayoutTransportersRouteWithChildren
  '/_login-layout/login': typeof LoginLayoutLoginRoute
  '/_dashboard-layout/': typeof DashboardLayoutIndexRoute
  '/_dashboard-layout/transporters/editor/$id': typeof DashboardLayoutTransportersEditorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/origins'
    | '/products'
    | '/territories'
    | '/transporters'
    | '/login'
    | '/transporters/editor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/origins'
    | '/products'
    | '/territories'
    | '/transporters'
    | '/login'
    | '/transporters/editor/$id'
  id:
    | '__root__'
    | '/_dashboard-layout'
    | '/_login-layout'
    | '/_dashboard-layout/categories'
    | '/_dashboard-layout/origins'
    | '/_dashboard-layout/products'
    | '/_dashboard-layout/territories'
    | '/_dashboard-layout/transporters'
    | '/_login-layout/login'
    | '/_dashboard-layout/'
    | '/_dashboard-layout/transporters/editor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  LoginLayoutRoute: typeof LoginLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_login-layout': {
      id: '/_login-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LoginLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard-layout': {
      id: '/_dashboard-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard-layout/': {
      id: '/_dashboard-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_login-layout/login': {
      id: '/_login-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLayoutLoginRouteImport
      parentRoute: typeof LoginLayoutRoute
    }
    '/_dashboard-layout/transporters': {
      id: '/_dashboard-layout/transporters'
      path: '/transporters'
      fullPath: '/transporters'
      preLoaderRoute: typeof DashboardLayoutTransportersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/territories': {
      id: '/_dashboard-layout/territories'
      path: '/territories'
      fullPath: '/territories'
      preLoaderRoute: typeof DashboardLayoutTerritoriesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/products': {
      id: '/_dashboard-layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashboardLayoutProductsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/origins': {
      id: '/_dashboard-layout/origins'
      path: '/origins'
      fullPath: '/origins'
      preLoaderRoute: typeof DashboardLayoutOriginsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/categories': {
      id: '/_dashboard-layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof DashboardLayoutCategoriesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/transporters/editor/$id': {
      id: '/_dashboard-layout/transporters/editor/$id'
      path: '/editor/$id'
      fullPath: '/transporters/editor/$id'
      preLoaderRoute: typeof DashboardLayoutTransportersEditorIdRouteImport
      parentRoute: typeof DashboardLayoutTransportersRoute
    }
  }
}

interface DashboardLayoutTransportersRouteChildren {
  DashboardLayoutTransportersEditorIdRoute: typeof DashboardLayoutTransportersEditorIdRoute
}

const DashboardLayoutTransportersRouteChildren: DashboardLayoutTransportersRouteChildren =
  {
    DashboardLayoutTransportersEditorIdRoute:
      DashboardLayoutTransportersEditorIdRoute,
  }

const DashboardLayoutTransportersRouteWithChildren =
  DashboardLayoutTransportersRoute._addFileChildren(
    DashboardLayoutTransportersRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardLayoutCategoriesRoute: typeof DashboardLayoutCategoriesRoute
  DashboardLayoutOriginsRoute: typeof DashboardLayoutOriginsRoute
  DashboardLayoutProductsRoute: typeof DashboardLayoutProductsRoute
  DashboardLayoutTerritoriesRoute: typeof DashboardLayoutTerritoriesRoute
  DashboardLayoutTransportersRoute: typeof DashboardLayoutTransportersRouteWithChildren
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutCategoriesRoute: DashboardLayoutCategoriesRoute,
  DashboardLayoutOriginsRoute: DashboardLayoutOriginsRoute,
  DashboardLayoutProductsRoute: DashboardLayoutProductsRoute,
  DashboardLayoutTerritoriesRoute: DashboardLayoutTerritoriesRoute,
  DashboardLayoutTransportersRoute:
    DashboardLayoutTransportersRouteWithChildren,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface LoginLayoutRouteChildren {
  LoginLayoutLoginRoute: typeof LoginLayoutLoginRoute
}

const LoginLayoutRouteChildren: LoginLayoutRouteChildren = {
  LoginLayoutLoginRoute: LoginLayoutLoginRoute,
}

const LoginLayoutRouteWithChildren = LoginLayoutRoute._addFileChildren(
  LoginLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  LoginLayoutRoute: LoginLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
